#!/bin/sh

next() {
    REMOTE=$(git remote)
	branch=$(git symbolic-ref "refs/remotes/$REMOTE/HEAD")
	if [ -z "$1" ]; then
		n=1
	else
		n=$1
	fi
	git log --reverse --pretty=%H "$branch" | grep -A $n $(git rev-parse HEAD) | tail -1 | xargs git checkout
}
next "$@"
